feat: stack arrays (test data in workspace stack_array_stuff)
devsoc-unsw/structs.sh pull request #652
Opened 2024-06-07 09:31 UTC by yellowsubmarine1447

Arrays on the stack. Stack arrays.

2024-06-13 08:28 UTC, dqna64 commented
verify:

![Screenshot 2024-06-13 at 18 26 25](https://github.com/devsoc-unsw/structs.sh/assets/76837291/3538c2ee-7b67-48ad-8938-ea1f46c4c63a)

![Screenshot 2024-06-13 at 18 27 42](https://github.com/devsoc-unsw/structs.sh/assets/76837291/7bc47a94-66f6-4c3f-beb8-913eb66145dc)

LGTM 👍 nice work guys :DD

2024-06-14 17:28 UTC, dqna64 commented
In integer reconstruction code, need to account for:

- endianness of system
- what data type is being reconstructed `(signed | unsigned) (short | int | float | double)` etc (signed values require two's complement in reconstruction code)

2024-06-14 17:33 UTC, dqna64 requested changes

2024-06-14 17:33 UTC, dqna64 commented on debugger/src/gdb_scripts/custom_next.py
> +            number = int(number) % 0x100
use `x/4ub addr` instead to get bytes in unsigned decimal format eg

```
(gdb) x/4b arr
0xaaaae40016b0:	-125	15	-52	-127

(gdb) x/4ub arr
0xaaaae40016b0:	131	15	204	129
```

2024-06-26 07:40 UTC, Shubh141 commented
lgtm

2024-06-26 07:49 UTC, Shubh141 approved these changes

2024-06-26 07:53 UTC, Shubh141 approved these changes

2024-06-26 07:54 UTC, Shubh141 approved these changes

2024-06-26 07:54 UTC, Shubh141 approved these changes

2024-06-26 07:55 UTC, Shubh141 approved these changes

2024-06-26 07:56 UTC, merged